---
title: "Managing R Package Dependencies"
description: "The R equivalent of requirements.txt in Python"
author: "Harel Lustiger"
date: '2020-03-27'
draft: yes
categories:
- R Projects
- Reproducible Research
slug: managing-r-package-dependencies-via-description
tags:
- Package Management    
- Reproducible Research    
- DESCRIPTION
link-citations: yes 
bibliography: [references-posts.bib]
biblio-style: apalike
---

<!-- Problem -->
<!-- Agitation -->
<!-- Solution -->
<!-- Outcome -->

# Overview

The approach in a nutshell:

1. Maintaining package requirements in a `DESCRIPTION` file; 
2. Setting the URL from which to pull the packages from via `options(repos =
"<MRAN-url>")`; and
3. Installing all required packages with `remotes::install_deps()`.

If you need a solution quickly, jump to 
["Putting Everything Together"](#conclusion) section to see code for a working
example.

<!-- talk about addind the dplyr package as a dependecncy -->

<!-- what is a dependency -->

# Introduction

## Understanding the principles of package management

<!-- theory -->

## Understanding the underline mechanism of package managers in R

<!-- * install.packages() -->

## Writing R Extensions

<!-- The DESCRIPTION file -->

<!-- Package Dependencies -->

## Using a de-jure Package Manager

<!-- Main feature -->

<!-- Advantages -->

# Managing R Packages via DESCRIPTION {#recipe}

## Getting Started

### Installing a tool kit for convenience

### Initiating the DESCRIPTION file

## Grooming the DESCRIPTION file 

### Adding package requirements from CRAN

### Adding package requirements outside CRAN

## Installing Package Requirements

### Emulating CRAN at a specific point in time

### Installing package dependencies

# Putting Everything Together {#conclusion}

Putting it all together, we get:

```{r conclusion, eval = FALSE, echo = TRUE}
###################################################################
## During project development use this code
###################################################################
# Installing a tool kit for convenience
install.packages(c("remotes", "usethis"))

## Initiating the DESCRIPTION file
usethis::use_description()

## Grooming the DESCRIPTION file
### add {ggplot2} as a requirement
usethis::use_package("ggplot2")
### add {dplyr} version 0.8.0 and above as a requirement
usethis::use_package("dplyr", min_version = "0.8.0") 

###################################################################
## During project deployment use this code
###################################################################
## Emulating CRAN at a specific point in time
options(repos = "https://mran.microsoft.com/snapshot/2020-03-27")
## Installing package dependencies
remotes::install_deps()
```

You could try running the yourself on RStudio cloud by 
[clicking here](https://rstudio.cloud/project/1179635).

# Reading more about the subject {#resources}

# References {#references}

