---
title: "About"
author: "Harel Lustiger"
description: "About Harel Lustiger"
slug: about
output:
  blogdown::html_page:
    number_sections: no
    toc: no
link-citations: yes 
bibliography: [../../inst/REFERENCES.bib]
biblio-style: [../../inst/harvard1.csl]
editor_options: 
  markdown: 
    wrap: 80
---

```{r, include = FALSE}
source(file.path(usethis::proj_get(), "vignettes",  "_common.R"))
```

# Foreword

I am a Senior Data Scientist with qualifications in Electronics Engineering and
Applied Statistics.

Neither of these qualifications have provided me with good practices of software
engineering. As a result, many of my data science projects were haphazardly
structured, sprawling, sloppy, duct-tape-and-baling-wire, spaghetti-code jungle.
Some projects were successful in producing the desired outcome. However, without
an appropriate software development approach in place, extending and maintaining
them required a substantial amount of time and effort.

Guided by an aspiration to minimise effort and maximise productivity, I embarked
on a quest for good data science practices in three domains: software
engineering, statistical analysis, and project management.

When reaching project milestones, I look back at my craft and reflect. What
approach/tool/technique worked well for the project? What did not work well?
What actions can I take to improve the software development process going
forward? It gives me pleasure to build a deeper understanding of the data
science domain and to formulate concrete next steps for present and future data
science projects.

This blog is part of my effort to document and communicate my findings and
insights. I hope readers will find these posts actionable and impactful.

# Writing Philosophy

## Goals

-   Maximum Real Value Added (RVA) time;

-   Minimum Business Value Added (BVA) time; and

-   Eliminate Non-Value Added (NVA) time.

```{=html}
<!-- 
Though value added is working software (or extra features), real value added
does not represent the usefulness of that working software.
-->
```
```{=html}
<!-- 
A software program that is hard to understand, requires more communication.
That means more time is spent on meetings or documentation (BVA).
-->
```
## Qualities

The six qualities of the Data Science teaching:

1.  It is not a speculative philosophy but an exposition of the governing forces
    in Data Science based on a causal analysis of past Data Science projects. It
    is taught, therefore, as a science rather than a belief system.

2.  It is open to scientific and other types of scrutiny and is not based on
    faith. It can be tested by personal practice and one who follows it will see
    the result for oneself by means of one's own experience.

3.  It is able to bestow immediate results here and now. There is no need to
    wait for the future or a next project.

4.  It invites all Data Scientists to put it to the test and come see for
    themselves.

```{=html}
<!-- 
## Principles 
 1.  Premature activities, including: 
     -   Premature optimization 
     -   Premature generalisation 
 2.  The complexity of software is an essential property, not an incidental one. 
Nonetheless, some complexity is neither necessary nor warranted. 
-->
```

--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`
