---
title: Package Management in R via DESCRIPTION
author: Harel Lustiger
date: '2020-03-27'
draft: true
slug: package-management-in-r-via-description
categories:
  - R Projects
  - Reproducible R
tags:
  - dependency management
  - package reproducibility
  - package management
bibliography: [references-posts.bib]
biblio-style: apalike
link-citations: yes  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  out.width = "100%"
)
```

## Synopsis

**In This Post**

* Using a package manager that capitalises existing infrastructure. 
* Forming a discipline of grooming the DESCRIPTION file
* Managing R package dependencies in Docker.

This post aims to find an efficient solution for managing packages of any
R-based application in conjunction with Docker. The proposed solution turns out
to be efficient even without using Docker. Thus, this post offers an efficient
solution for managing packages of R-based application.

The suggested solution uses an underpinning mechanism that is being used by all
R packages. In short, any R package declares its needs in a file called
DESCRIPTION. DESCRIPTION comprises package metadata organised in fields and
values pairs. In particular, there is one field named "Imports" which lists
packages dependencies: names and (optionally) minimum versions.

The suggested solution adds two optional fields to the DESCRIPTION file: Lib and
Repos. Lib specifies where to install the packages; Repos specifies URL(s) from
which the packages are downloaded from. Importantly, the URL can point to a
snapshot of packages versions which were existed on a specific date.

## Package Manager Elements

The basic and most common method to install R packages is using
`install.packages()`. Looking at the function help documentation, the first
three input arguments are:

1. `pkgs`
2. `lib`
3. `repos`

```
install.packages(pkgs, lib, repos = getOption("repos"),
                 contriburl = contrib.url(repos, type),
                 method, available = NULL, destdir = NULL,
                 dependencies = NA, type = getOption("pkgType"),
                 configure.args = getOption("configure.args"),
                 configure.vars = getOption("configure.vars"),
                 clean = FALSE, Ncpus = getOption("Ncpus", 1L),
                 verbose = getOption("verbose"),
                 libs_only = FALSE, INSTALL_opts, quiet = FALSE,
                 keep_outputs = FALSE, ...)
```

## The DESCRIPTION File

Whether you are aware of it or not, your R application uses DESCRIPTION files.
This is because every R package must have one DESCRIPTION file that conforms
with the "Writing R extensions" protocol dictated by the R Core
Team[@team1999writing]. 

The following is a DESCRIPTION file excerpt of the
[`ggplot2`](https://github.com/tidyverse/ggplot2/blob/v3.3.0/DESCRIPTION)
package:

```
Package: ggplot2
Version: 3.3.0
Title: Create Elegant Data Visualisations Using the Grammar of Graphics
Description: A system for 'declaratively' creating graphics,
    based on "The Grammar of Graphics". You provide the data, tell 'ggplot2'
    how to map variables to aesthetics, what graphical primitives to use,
    and it takes care of the details.
Authors@R: person("Hadley","Wickham", ,"hadley@rstudio.com",c("aut", "cre"))
Imports: 
    digest,
    glue,
    grDevices,
    grid,
    gtable (>= 0.1.1),
    isoband,
    MASS,
    mgcv,
    rlang (>= 0.3.0),
    scales (>= 0.5.0),
    stats,
    tibble,
    withr (>= 2.0.0)
```



## References